import { z } from "zod";

/**
 * Zod schema for validating individual steps generated by the AI
 */
export const AIStepSchema = z.object({
  title: z.string().min(1, "Step title cannot be empty"),
  instruction: z.string().min(1, "Step instruction cannot be empty"),
  actionType: z.enum(["click", "input", "hover", "select", "wait", "navigate", "code_highlight"]),
  selector: z.string().default(""),
  url: z.string().default(""),
  metadata: z.record(z.string(), z.any()).default({}),
});

/**
 * Zod schema for validating the full tutorial structure generated by the AI
 */
export const AITutorialSchema = z.object({
  title: z.string().min(1, "Tutorial title cannot be empty"),
  description: z.string().default(""),
  estimatedTime: z.number().default(5),
  difficulty: z.enum(["Beginner", "Intermediate", "Advanced"]).default("Beginner"),
  domain: z.string().default(""),
  urlPattern: z.string().default(""),
  steps: z.array(AIStepSchema),
});

export type AIStep = z.infer<typeof AIStepSchema>;
export type AITutorial = z.infer<typeof AITutorialSchema>;
export type AISourceType = "youtube" | "website" | "upload";
